main:
  repo: https://github.com/romanAVJ/house-prices-mcd
  branch: main
etl:
  prep:
    arguments:
      csv_file_path:
        help: Path to the CSV file
        default: data/raw/train.csv
      save_file:
        help: Name to save the cleaned data
        default: house_data
      subset:
        help: Wether to subset the data with the given config file
        default: true
    variables:
      - Id
      - CurrentAge
      - LotArea
      - PorchArea
      - TotalBaths
      - OverallQual
      - OverallCond
      - GrLivArea
      - SaleType
      - SaleCondition
      - MSZoning
      - Story
      - StoryFinish
      - SalePrice
      - TotRmsAbvGrd
    current_year: 2010
    filters:
      TotRmsAbvGrd:
          operator: '>'
          value: 0
      TotalBaths:
          operator: '>'
          value: 0
      LotArea:
          operator: '<'
          value: 200000
      PorchArea:
          operator: '<'
          value: 1000
      SaleType:
          operator: 'in'
          value: ['WD', 'New']
      SaleCondition:
          operator: 'in'
          value: ['Normal', 'Partial']
      MSZoning:
          operator: 'in'
          value: ['RL', 'RM', 'RP', 'RH']
    save_path: data/clean/
  train:
    arguments:
      csv_file_path:
        help: Path to the CSV file
        default: data/clean/house_data.csv
      test_size:
        help: Proportion of the dataset to include in the test split
        default: 0.2
      name_model:
        help: Name to save the model
        default: charmander
      evaluate:
        help: Wether to evaluate the model
        default: true
    target_variable: SalePrice
    stratify:
      - MSZoning
    seed: 42
  inference:
    arguments:
      csv_file_path:
        help: Path to the CSV file
        default: data/clean/house_data.csv
      model_path:
        help: Path to the model
        default: models/catboost_demo/
      evaluate:
        help: Wether to evaluate the model
        default: true
      save_file:
        help: Name to save the predictions
        default: predictions
model:
  algorithm: catboost
  variables:
    categorical:
      - MSZoning
    numerical:
      - GrLivArea
      - OverallQual
      - CurrentAge
      - OverallCond
      - LotArea
  hyperparams:
    iterations: 1000
    learning_rate: 0.05
    loss_function: RMSE
    verbose: False
    random_seed: 42
    monotone_constraints:
      GrLivArea: 1
      OverallQual: 1
      CurrentAge: -1
      OverallCond: 1
      LotArea: 1
